[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
grant_evaluator = "2RC6cF4pmnANHAPkpoR2RcPm79Zgq8G9Sz9JKotGMvS6"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test"

[hooks]
