[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
grant_evaluator = "HF8HvTN2eEvSZ7LG1jmN5HvVWco8ufzHnZtkQnqDC8SG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test"

[hooks]
