[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
grant_evaluator = "CvjtrjA1yTdakHYxc77cfEsDHGiBDpKgQXhNXns9YVas"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test"

[hooks]
