import type { Criterion } from "@ipe-city/common";

/**
 * Core criteria — always applied to every proposal.
 */
export const CORE_CRITERIA: Criterion[] = [
  {
    criterionId: "security",
    name: "Security",
    description: "Technical risk assessment, attack surface analysis, and safety evaluation",
    category: "Security",
    weight: 2500,
    isCore: true,
    applicableDomains: [],
    evaluationGuidelines:
      "Assess smart contract risks, data privacy (LGPD), attack vectors, single points of failure, key management, and economic manipulation potential.",
    evidenceRequirements: ["Technical architecture details", "Security measures described"],
  },
  {
    criterionId: "impact",
    name: "Impact",
    description: "Measurable outcomes, scalability, sustainability, and beneficiary reach",
    category: "Impact",
    weight: 3000,
    isCore: true,
    applicableDomains: [],
    evaluationGuidelines:
      "Demand specific KPIs, evaluate timeline realism, assess sustainability beyond grant period, check cost-effectiveness.",
    evidenceRequirements: ["Defined KPIs or metrics", "Timeline with milestones"],
  },
  {
    criterionId: "alignment",
    name: "IPE City Alignment",
    description: "Alignment with IPE City values, PULSE integration, and governance contribution",
    category: "Alignment",
    weight: 2000,
    isCore: true,
    applicableDomains: [],
    evaluationGuidelines:
      "Check genuine vs superficial alignment, PULSE integration potential, on-chain reputation compatibility, freedom and autonomy principles.",
    evidenceRequirements: ["Connection to IPE City pillars", "Community benefit description"],
  },
];

/**
 * Adaptive criteria pool — selected per proposal based on domain.
 */
export const ADAPTIVE_CRITERIA: Criterion[] = [
  {
    criterionId: "defi-liquidity-risk",
    name: "Liquidity Risk",
    description: "Assessment of liquidity assumptions, oracle dependencies, and economic mechanism soundness",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["DeFi"],
    evaluationGuidelines: "Evaluate oracle dependency, liquidity depth assumptions, flash loan attack vectors, economic game theory.",
    evidenceRequirements: ["Liquidity analysis", "Oracle design"],
  },
  {
    criterionId: "defi-regulatory",
    name: "Regulatory Exposure",
    description: "Assessment of regulatory risks and compliance considerations",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["DeFi"],
    evaluationGuidelines: "Evaluate KYC/AML considerations, securities law implications, cross-border regulatory risks.",
    evidenceRequirements: ["Regulatory consideration mentioned"],
  },
  {
    criterionId: "governance-sybil",
    name: "Sybil Resistance",
    description: "Resistance to identity manipulation and vote manipulation",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["Governance"],
    evaluationGuidelines: "Assess identity verification mechanisms, vote weighting design, delegation safety.",
    evidenceRequirements: ["Identity or voting mechanism described"],
  },
  {
    criterionId: "governance-decentralization",
    name: "Power Decentralization",
    description: "Distribution of control and avoidance of power concentration",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["Governance"],
    evaluationGuidelines: "Evaluate admin key design, upgrade mechanisms, veto powers, minimum participation thresholds.",
    evidenceRequirements: ["Governance structure described"],
  },
  {
    criterionId: "education-pedagogy",
    name: "Pedagogy Methodology",
    description: "Quality of teaching approach and learning outcome measurement",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["Education"],
    evaluationGuidelines: "Assess learning outcome definitions, assessment methods, accessibility considerations.",
    evidenceRequirements: ["Learning outcomes defined"],
  },
  {
    criterionId: "education-accessibility",
    name: "Accessibility",
    description: "Inclusivity of the educational approach across skill levels and backgrounds",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["Education"],
    evaluationGuidelines: "Evaluate language accessibility, prerequisite assumptions, accommodation for different learning styles.",
    evidenceRequirements: ["Target audience defined"],
  },
  {
    criterionId: "health-data-ethics",
    name: "Data Ethics",
    description: "Ethical handling of health data, privacy protections, and consent mechanisms",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["Health"],
    evaluationGuidelines: "Assess LGPD compliance, informed consent design, data minimization, anonymization.",
    evidenceRequirements: ["Data handling policy described"],
  },
  {
    criterionId: "health-equity",
    name: "Health Equity",
    description: "Equitable access to health benefits across community segments",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["Health"],
    evaluationGuidelines: "Evaluate access barriers, cost considerations, geographic limitations.",
    evidenceRequirements: ["Access strategy described"],
  },
  {
    criterionId: "infra-reliability",
    name: "Reliability SLA",
    description: "System uptime guarantees, failure modes, and maintenance planning",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["Infrastructure"],
    evaluationGuidelines: "Assess uptime targets, disaster recovery, monitoring, alerting, redundancy design.",
    evidenceRequirements: ["Availability targets defined"],
  },
  {
    criterionId: "infra-interoperability",
    name: "Interoperability",
    description: "Ability to integrate with existing IPE City infrastructure and external systems",
    category: "Adaptive",
    weight: 1250,
    isCore: false,
    applicableDomains: ["Infrastructure"],
    evaluationGuidelines: "Evaluate API design, standard compliance, backward compatibility, migration paths.",
    evidenceRequirements: ["Integration points described"],
  },
];
